### ISSUE TITLE
pytimeparse/pytimeparse2/cpptimeparse

### ISSUE THREAD

**Issue by wiluite** [paulo-raca/ideas#2]
Hi!
I saw, sometime ago you were curious about 'microsecond support' in pytimeparse/pytimeparse2. 

cpptimeparse is an attempt to create similar code to pytimeparse but in c++ (with python bindings for who interested) for myself's future tasks.

https://github.com/wiluite/cpptimeparse

You can share your impressions about its correctness and performance (if there is a huge data set). (But I will hardly support nanoseconds.)
I did not check it in Linux with code sanitizers for now. But I am doing it these days.

**Comment by paulo-raca** [comment]
Neat, thanks for sharing!
